### PR TITLE
Fix build warnings

### LINKED ISSUE #121: Clean up build warnings
image

### PR DESCRIPTION
**Pull request by am-MongoDB**
fixes #121

### CODE REVIEW

File: o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift [hunk 1]
```diff
@@ -62,9 +59,9 @@ struct PatrolSummaryView: View {
             VStack(spacing: .zero) {
                 CallToActionButton(title: "Go Off Duty",
                     action: self.goOffDutyClicked)
-                    .padding(.top, Dimensions.Button.topPadding)
-                    .padding(.bottom, Dimensions.Button.bottomPadding)
-                    .padding(.horizontal, Dimensions.Button.leadingTrailingPadding)
+                    .padding(.top, Dimensions.buttonTopPadding)
```
Comment (kojiba) [inline o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift:62]: not sure about this, for me nested enum for specific configuration has better readability

Comment (am-MongoDB) [reply o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift:62]: We should change this or add it to the exceptions in our SwiftLint file – either is OK with me, but we should get rid of the build warnings as they may mask something more serious

Comment (kojiba) [reply o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolSummaryView.swift:62]: lets keep it for this PR, I will take a look in next PR for swiftlint update
