### PR TITLE
Not at sea and drafts

### LINKED ISSUE #299: Not at sea and drafts
When a user with drafts changes status to 'Not at Sea' the patrol summary should appear with the addition of a total number of drafts and a dot next to each boarding record that is a draft. The color should be the same orange as the validation exceptions. From that page the user can select a boarding record to see the summary (whether or not it is a draft) or continue as usual or cancel. If a user wants to edit a draft record they will be trained to cancel and go to the home screeen where the draft boardings are. https://mongodb.invisionapp.com/share/M6YN2Y77B8E#/screens/430523456_Home-On_Duty-5_Unsaved

### PR DESCRIPTION
**Pull request by akaktus**
[-] Implemented not at sea with drafts
[-] Fixed rounded size.
Fixes #299, #320

### CODE REVIEW

**Review by MykytaKiriushyn — APPROVED** [review]

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/LIywX167/325-review-prs)

**Comment by o-fish-wildaid** [comment]
[Review PRs](https://trello.com/c/QKVtiwN0/372-review-prs)

**Comment by am-MongoDB** [comment]
When going off duty, the number of drafts isn't displayed and the Draft report ("Draft Punk" here) doesn't have an orange dot
image

File: o-fish-ios/Views/Components/SegmentedField.swift [hunk 1]
```diff
@@ -47,7 +48,7 @@ struct SegmentedField: View {
                         }
                             .frame(height: Dimensions.heightButton)
                             .background(self.selectedItem == item ? self.activeColor : self.secondaryColor)
-                            .cornerRadius(.infinity)
+                            .cornerRadius(25)
```
Comment (am-MongoDB) [inline o-fish-ios/Views/Components/SegmentedField.swift:51]: Should use a value from `Dimensions` rather than using `25`

File: o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift [hunk 2]
```diff
@@ -10,6 +10,7 @@ import SwiftUI
 struct PatrolReportView: View {
 
     var report: ReportViewModel
+    var showingOnSummary = false
```
Comment (am-MongoDB) [inline o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift:13]: Why is this needed? Only `true` is ever passed to this view

File: o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift [hunk 3]
```diff
@@ -61,6 +73,9 @@ struct PatrolReportView: View {
 
 struct PatrolReportView_Previews: PreviewProvider {
     static var previews: some View {
+        VStack {
         PatrolReportView(report: .sample)
+            PatrolReportView(report: .sample, showingOnSummary: true)
+        }
     }
 }
```
Comment (am-MongoDB) [inline o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift:81]:
```
struct PatrolReportView_Previews: PreviewProvider {
    static var previews: some View {
        let draftReport: ReportViewModel = .sample
        draftReport.draft = true
        return VStack {
            PatrolReportView(report: .sample)
            PatrolReportView(report: .sample, showingOnSummary: true)
            PatrolReportView(report: draftReport, showingOnSummary: true)
        }
    }
}
```

**Review by am-MongoDB — CHANGES_REQUESTED** [review]

File: o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift (hunk 2 above)
Comment (akaktus) [reply o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift:13]: We use PatrolReportView on DraftBoardingLoadedStateView, with  false by default, and on PatrolSummaryView with parameter true. So this parameter is needed.

Comment (am-MongoDB) [reply o-fish-ios/Views/PatrolBoat/PatrolSummary/PatrolReportView.swift:13]: Ah - that makes sense – `DraftBoardingLoadedStateView` isn't in this branch and so Xcode couldn't find the reference!
